declare interface UzumTransactionModelI {
  id: number;
  payment_order: number;
  card_transaction: number | null;
  uzum_order_id: string;
  merchant_operation_id: string | null;
  order_number: string;
  amount: number;
  redirect_url: string | null;
  service_id: number | null;
  state: import("./enums").UzumTransactionStateTypes;
  operation_type: string | null;
  rrn: string | null;
  card_type: number | null;
  binding_id: string | null;
  payment_source: string | null;
  tariff: string | null;
  processing_reference_number: string | null;
  phone: string | null;
  raw_callback: Record<string, unknown> | null;
  raw_create: Record<string, unknown> | null;
  raw_confirm: Record<string, unknown> | null;
  raw_reverse: Record<string, unknown> | null;
  registered_at: Date;
  completed_at: Date | null;
  declined_at: Date | null;
  refunded_at: Date | null;
  createdAt?: Date;
  updatedAt?: Date;
}
